### ISSUE TITLE
Getting the  DidYouMean::SPELL_CHECKERS.merge!(    Error

### ISSUE THREAD

**Issue by leonaAtkins** [andrew/ruby-upgrade-action#1]
Thank you for this action, I'm hoping this will save us a lot of time updating repos.
However when I try an run it I get
```
Updated .ruby-version file
/opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/gems/3.4.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/error.rb:105:in '<class:Thor>': uninitialized constant DidYouMean::SPELL_CHECKERS (NameError)

    DidYouMean::SPELL_CHECKERS.merge!(
              ^^^^^^^^^^^^^^^^
Did you mean?  DidYouMean::SpellChecker
	from /opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/gems/3.4.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/error.rb:1:in '<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/gems/3.4.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/base.rb:3:in 'Kernel#require_relative'
	from /opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/gems/3.4.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor/base.rb:3:in '<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/gems/3.4.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor.rb:1:in 'Kernel#require_relative'
	from /opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/gems/3.4.0/gems/bundler-2.2.22/lib/bundler/vendor/thor/lib/thor.rb:1:in '<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/gems/3.4.0/gems/bundler-2.2.22/lib/bundler/vendored_thor.rb:8:in 'Kernel#require_relative'
	from /opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/gems/3.4.0/gems/bundler-2.2.22/lib/bundler/vendored_thor.rb:8:in '<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/gems/3.4.0/gems/bundler-2.2.22/lib/bundler/friendly_errors.rb:3:in 'Kernel#require_relative'
	from /opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/gems/3.4.0/gems/bundler-2.2.22/lib/bundler/friendly_errors.rb:3:in '<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/gems/3.4.0/gems/bundler-2.2.22/exe/bundle:32:in 'Kernel#require_relative'
	from /opt/hostedtoolcache/Ruby/3.4.4/x64/lib/ruby/gems/3.4.0/gems/bundler-2.2.22/exe/bundle:32:in '<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.4.4/x64/bin/bundle:25:in 'Kernel#load'
	from /opt/hostedtoolcache/Ruby/3.4.4/x64/bin/bundle:25:in '<main>'
```

My Action config
```
name: Upgrade Ruby

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * 0" # Runs Monthly

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: andrew/ruby-upgrade-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

Any idea what is causing this and how I can fix it?
